services:
  - type: worker
    name: makima-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OWNER_ID
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: MONGO_DB
        value: makima_bot
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHON_VERSION
        value: "3.12.0"
